export const SET_USER_PROFILE = 'SET_USER_PROFILE'
export const SET_USER_FAVORITES = 'SET_USER_FAVORITES'
export const UPDATE_USER_FAVORITES = 'UPDATE_USER_FAVORITES'
export const LOGOUT = 'LOGOUT'


export const UPDATE_PLAYING_SONG = 'UPDATE_PLAYING_SONG'
export const UPDATE_PLAYING_ALBUM = 'UPDATE_PLAYING_ALBUM'
export const UPDATE_HEARTBEAT_ALBUM = 'UPDATE_HEARTBEAT_ALBUM'
export const UPDATE_PLAYING_MODE = 'UPDATE_PLAYING_MODE'
export const NEXT_SONG = 'NEXT_SONG'
export const PREV_SONG = 'PREV_SONG'


export const UPDATE_HOME_CONTENT = 'UPDATE_HOME_CONTENT'