export const SAVE_USER_PROFILE = 'SAVE_USER_PROFILE'


export const UPDATE_PLAYING_SONG = 'UPDATE_PLAYING_SONG'
export const UPDATE_PLAYING_LIST = 'UPDATE_PLAYING_LIST'
export const UPDATE_PLAYING_MODE = 'UPDATE_PLAYING_MODE'
export const NEXT_SONG = 'NEXT_SONG'
export const PREV_SONG = 'PREV_SONG'